<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<script src="load.js"></script>
<script src="jquery-3.4.1.min.js"></script>
<script src="tooltip.min.js"></script>
<script src="popper.min.js"></script>
<script src="bootstrap.min.js"></script>

<link rel="stylesheet" type="text/css" href="estilos.css" />
<link rel="stylesheet" href="bootstrap.min.css"/>